import type { Ingredient, Product, Procedure, JournalEntry, UserProfile } from './types';

export const INGREDIENTS: Ingredient[] = [
  {
    id: 'niacinamide',
    name: 'Niacinamide',
    inci: 'Niacinamide',
    category: 'Vitamin',
    whatItDoes: 'A form of Vitamin B3 that regulates sebum production, minimizes pores, fades dark spots, and strengthens the skin barrier.',
    benefits: ['Minimizes pores', 'Controls oil', 'Fades hyperpigmentation', 'Brightens skin', 'Strengthens barrier', 'Reduces inflammation'],
    potentialConcerns: ['May cause flushing at high concentrations (>10%)', 'Theoretical conflict with Vitamin C (largely debunked)'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['oily', 'combination', 'normal', 'sensitive'],
    concerns: ['hyperpigmentation', 'pores', 'acne', 'dullness'],
    notes: 'One of the most well-studied and versatile skincare ingredients.',
  },
  {
    id: 'retinol',
    name: 'Retinol',
    inci: 'Retinol',
    category: 'Retinoid',
    whatItDoes: 'A Vitamin A derivative that accelerates cell turnover, stimulates collagen production, and treats acne and signs of aging.',
    benefits: ['Reduces fine lines', 'Stimulates collagen', 'Treats acne', 'Evens skin tone', 'Refines texture', 'Fades dark spots'],
    potentialConcerns: ['Irritation and peeling (especially initially)', 'Sun sensitivity — must use SPF', 'Not safe during pregnancy', 'Avoid mixing with AHA/BHA in same routine step'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['normal', 'oily', 'combination'],
    concerns: ['anti-aging', 'acne', 'hyperpigmentation', 'texture', 'fine-lines'],
  },
  {
    id: 'hyaluronic-acid',
    name: 'Hyaluronic Acid',
    inci: 'Sodium Hyaluronate',
    category: 'Humectant',
    whatItDoes: 'A powerful humectant that attracts and retains water, holding up to 1000x its weight in moisture.',
    benefits: ['Deep hydration', 'Plumps skin', 'Reduces fine lines', 'Soothing', 'Works for all skin types'],
    potentialConcerns: ['Can draw moisture from skin in dry climates if not topped with occlusives', 'Different molecular weights penetrate to different depths'],
    evidenceLevel: 'strong',
    isActive: false,
    skinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive'],
    concerns: ['dryness', 'fine-lines', 'firmness'],
  },
  {
    id: 'vitamin-c',
    name: 'Vitamin C (L-Ascorbic Acid)',
    inci: 'Ascorbic Acid',
    category: 'Antioxidant',
    whatItDoes: 'A potent antioxidant that brightens skin, inhibits melanin production, and boosts collagen synthesis.',
    benefits: ['Brightens complexion', 'Fades dark spots', 'Antioxidant protection', 'Boosts collagen', 'Protects against UV damage'],
    potentialConcerns: ['Unstable — degrades quickly', 'Can be irritating at high concentrations', 'Avoid mixing with niacinamide (theoretical flushing)', 'Low pH required for efficacy'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['normal', 'dry', 'combination', 'oily'],
    concerns: ['hyperpigmentation', 'dullness', 'anti-aging', 'fine-lines'],
  },
  {
    id: 'glycolic-acid',
    name: 'Glycolic Acid',
    inci: 'Glycolic Acid',
    category: 'AHA',
    whatItDoes: 'The smallest AHA, it exfoliates by loosening the bonds between dead skin cells, improving texture and tone.',
    benefits: ['Exfoliates', 'Improves texture', 'Brightens', 'Fades hyperpigmentation', 'Reduces acne', 'Stimulates collagen'],
    potentialConcerns: ['Increases sun sensitivity', 'Can be irritating for sensitive skin', 'Do not use with retinol in same step', 'Risk of over-exfoliation'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['normal', 'oily', 'combination'],
    concerns: ['hyperpigmentation', 'texture', 'acne', 'dullness'],
  },
  {
    id: 'salicylic-acid',
    name: 'Salicylic Acid (BHA)',
    inci: 'Salicylic Acid',
    category: 'BHA',
    whatItDoes: 'An oil-soluble beta hydroxy acid that penetrates pores to exfoliate, making it ideal for acne-prone and oily skin.',
    benefits: ['Clears pores', 'Reduces blackheads', 'Treats acne', 'Exfoliates', 'Anti-inflammatory', 'Controls oil'],
    potentialConcerns: ['Drying at high concentrations', 'Increases sun sensitivity', 'Not recommended during pregnancy'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['oily', 'combination'],
    concerns: ['acne', 'pores', 'texture'],
  },
  {
    id: 'ceramides',
    name: 'Ceramides',
    inci: 'Ceramide NP, Ceramide AP, Ceramide EOP',
    category: 'Barrier Repair',
    whatItDoes: 'Lipid molecules naturally found in the skin barrier. Replenish lost ceramides to strengthen and repair the barrier.',
    benefits: ['Strengthens barrier', 'Prevents TEWL', 'Soothes irritation', 'Improves hydration', 'Helps with eczema/sensitivity'],
    potentialConcerns: ['Generally very well tolerated', 'No significant concerns'],
    evidenceLevel: 'strong',
    isActive: false,
    skinTypes: ['dry', 'sensitive', 'normal', 'combination'],
    concerns: ['dryness', 'sensitivity', 'redness'],
  },
  {
    id: 'peptides',
    name: 'Peptides',
    inci: 'Palmitoyl Tripeptide-1, Acetyl Hexapeptide-3',
    category: 'Peptide',
    whatItDoes: 'Short chains of amino acids that signal skin to produce collagen and elastin, reducing signs of aging.',
    benefits: ['Stimulates collagen', 'Reduces wrinkles', 'Firms skin', 'Improves elasticity', 'Hydrating'],
    potentialConcerns: ['Unstable in some formulations', 'Results take months to appear', 'Can be broken down by enzymes'],
    evidenceLevel: 'moderate',
    isActive: true,
    skinTypes: ['normal', 'dry', 'combination', 'sensitive'],
    concerns: ['anti-aging', 'fine-lines', 'firmness'],
  },
  {
    id: 'azelaic-acid',
    name: 'Azelaic Acid',
    inci: 'Azelaic Acid',
    category: 'Acid',
    whatItDoes: 'A dicarboxylic acid with antibacterial and anti-inflammatory properties, effective for rosacea and hyperpigmentation.',
    benefits: ['Reduces rosacea', 'Fades hyperpigmentation', 'Treats acne', 'Anti-inflammatory', 'Gentle on sensitive skin'],
    potentialConcerns: ['Tingling sensation initially', 'Can be drying at high percentages'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['sensitive', 'normal', 'combination'],
    concerns: ['redness', 'hyperpigmentation', 'acne', 'sensitivity'],
  },
  {
    id: 'squalane',
    name: 'Squalane',
    inci: 'Squalane',
    category: 'Emollient',
    whatItDoes: 'A stable, lightweight emollient derived from olives or sugarcane that mimics skin\'s natural oils.',
    benefits: ['Deeply moisturizing', 'Non-comedogenic', 'Antioxidant', 'Improves elasticity', 'Suitable for all skin types'],
    potentialConcerns: ['Very well tolerated', 'Minimal concerns'],
    evidenceLevel: 'moderate',
    isActive: false,
    skinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive'],
    concerns: ['dryness', 'anti-aging'],
  },
  {
    id: 'retinal',
    name: 'Retinaldehyde',
    inci: 'Retinaldehyde',
    category: 'Retinoid',
    whatItDoes: 'One step closer to retinoic acid than retinol, more potent with faster results and less irritation than prescription retinoids.',
    benefits: ['Faster results than retinol', 'Antimicrobial', 'Reduces wrinkles', 'Stimulates collagen', 'Treats acne'],
    potentialConcerns: ['More irritating than retinol', 'Sun sensitivity', 'Not safe in pregnancy', 'Less stable than retinol'],
    evidenceLevel: 'moderate',
    isActive: true,
    skinTypes: ['normal', 'oily', 'combination'],
    concerns: ['anti-aging', 'acne', 'fine-lines', 'texture'],
  },
  {
    id: 'spf',
    name: 'Broad Spectrum SPF',
    inci: 'Zinc Oxide / Titanium Dioxide / Avobenzone',
    category: 'Photoprotection',
    whatItDoes: 'Protects against UVA and UVB radiation, preventing photoaging, hyperpigmentation, and skin cancer.',
    benefits: ['Prevents photoaging', 'Prevents hyperpigmentation', 'Cancer prevention', 'Preserves all other skincare results'],
    potentialConcerns: ['Chemical filters may cause irritation', 'Physical filters can leave white cast', 'Must be reapplied every 2 hours'],
    evidenceLevel: 'strong',
    isActive: true,
    skinTypes: ['dry', 'oily', 'combination', 'normal', 'sensitive'],
    concerns: ['anti-aging', 'hyperpigmentation', 'sensitivity'],
  },
  {
    id: 'tranexamic-acid',
    name: 'Tranexamic Acid',
    inci: 'Tranexamic Acid',
    category: 'Brightening',
    whatItDoes: 'Inhibits melanin production pathways, effective for melasma and hyperpigmentation with minimal irritation.',
    benefits: ['Fades melasma', 'Reduces hyperpigmentation', 'Gentle on sensitive skin', 'Can be used during pregnancy'],
    potentialConcerns: ['Slower results than other brighteners', 'Emerging evidence still building'],
    evidenceLevel: 'emerging',
    isActive: true,
    skinTypes: ['sensitive', 'normal', 'dry', 'combination'],
    concerns: ['hyperpigmentation', 'dullness', 'redness'],
  },
  {
    id: 'centella',
    name: 'Centella Asiatica (Cica)',
    inci: 'Centella Asiatica Extract',
    category: 'Botanical',
    whatItDoes: 'A calming botanical extract that soothes irritation, promotes wound healing, and strengthens the skin barrier.',
    benefits: ['Soothes irritation', 'Promotes healing', 'Strengthens barrier', 'Anti-inflammatory', 'Stimulates collagen'],
    potentialConcerns: ['Rare allergic reactions possible', 'Variable quality between sources'],
    evidenceLevel: 'moderate',
    isActive: false,
    skinTypes: ['sensitive', 'normal', 'dry'],
    concerns: ['redness', 'sensitivity', 'acne'],
  },
  {
    id: 'bakuchiol',
    name: 'Bakuchiol',
    inci: 'Bakuchiol',
    category: 'Retinol Alternative',
    whatItDoes: 'A plant-derived retinol alternative that provides similar anti-aging benefits with less irritation.',
    benefits: ['Reduces fine lines', 'Brightens skin', 'Firming', 'Safe during pregnancy', 'Less irritating than retinol'],
    potentialConcerns: ['Less research than retinol', 'Results may be slower'],
    evidenceLevel: 'emerging',
    isActive: true,
    skinTypes: ['sensitive', 'dry', 'normal', 'combination'],
    concerns: ['anti-aging', 'fine-lines', 'firmness', 'sensitivity'],
  },
];

export const PRODUCTS: Product[] = [
  {
    id: 'cerave-cleanser',
    name: 'Hydrating Facial Cleanser',
    brand: 'CeraVe',
    category: 'cleanser',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=300&h=300&fit=crop',
    imageColor: '#E8F4F8',
    price: 16,
    size: '473ml',
    purchaseDate: '2024-01-15',
    openedDate: '2024-01-20',
    paoMonths: 12,
    concerns: ['dryness', 'sensitivity'],
    ingredients: ['ceramides', 'hyaluronic-acid', 'niacinamide'],
    keyIngredients: ['ceramides', 'hyaluronic-acid', 'niacinamide'],
    rating: {
      overall: 4.5,
      texture: 4,
      efficacy: 4.5,
      value: 5,
      pros: ['Gentle', 'Doesn\'t strip skin', 'Affordable', 'Good size'],
      cons: ['Can feel slightly heavy in summer'],
      notes: 'My holy grail cleanser. Super gentle, cleans well without stripping. Perfect for AM and PM.',
      adverseReactions: [],
      wouldRepurchase: true,
      reviewDate: '2024-06-01',
    },
    inRoutine: true,
    routineStep: 'both',
    routineOrder: 1,
    tags: ['gentle', 'hydrating', 'fragrance-free', 'budget-friendly'],
  },
  {
    id: 'paula-niacinamide',
    name: '10% Niacinamide Booster',
    brand: "Paula's Choice",
    category: 'serum',
    imageUrl: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=300&h=300&fit=crop',
    imageColor: '#FFF8E7',
    price: 44,
    size: '20ml',
    purchaseDate: '2024-02-01',
    openedDate: '2024-02-05',
    paoMonths: 12,
    concerns: ['pores', 'acne', 'hyperpigmentation', 'dullness'],
    ingredients: ['niacinamide'],
    keyIngredients: ['niacinamide'],
    rating: {
      overall: 4,
      texture: 4.5,
      efficacy: 4,
      value: 3,
      pros: ['Noticeably minimized pores', 'Controls shine', 'Lightweight texture'],
      cons: ['Pricey for the size', 'Takes 4-6 weeks to see results'],
      notes: 'Works well layered under moisturizer. Saw improvement in pore appearance after 6 weeks.',
      adverseReactions: [],
      wouldRepurchase: true,
      reviewDate: '2024-06-15',
    },
    inRoutine: true,
    routineStep: 'both',
    routineOrder: 3,
    tags: ['pore-minimizing', 'brightening', 'oil-control'],
  },
  {
    id: 'ordinary-retinol',
    name: 'Retinol 0.5% in Squalane',
    brand: 'The Ordinary',
    category: 'treatment',
    imageUrl: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=300&h=300&fit=crop',
    imageColor: '#F5F5F5',
    price: 7,
    size: '30ml',
    purchaseDate: '2024-03-01',
    openedDate: '2024-03-10',
    paoMonths: 12,
    concerns: ['anti-aging', 'texture', 'fine-lines', 'acne'],
    ingredients: ['retinol', 'squalane'],
    keyIngredients: ['retinol'],
    rating: {
      overall: 4,
      texture: 4.5,
      efficacy: 4,
      value: 5,
      pros: ['Incredible value', 'Squalane base is moisturizing', 'Effective concentration for beginners'],
      cons: ['Initial purging phase', 'Some peeling in first 2 weeks'],
      notes: 'Started 2x/week, now using 4x/week. Skin texture has significantly improved. Some redness when started.',
      adverseReactions: ['Mild peeling weeks 1-2', 'Slight redness initially'],
      wouldRepurchase: true,
      reviewDate: '2024-07-01',
    },
    inRoutine: true,
    routineStep: 'pm',
    routineOrder: 4,
    tags: ['anti-aging', 'acne', 'starter-retinol', 'budget-friendly'],
  },
  {
    id: 'skinceuticals-vitamin-c',
    name: 'C E Ferulic Serum',
    brand: 'SkinCeuticals',
    category: 'serum',
    imageUrl: 'https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=300&h=300&fit=crop',
    imageColor: '#FFFBF0',
    price: 185,
    size: '30ml',
    purchaseDate: '2024-04-01',
    openedDate: '2024-04-05',
    paoMonths: 3,
    expiryDate: '2024-07-05',
    concerns: ['hyperpigmentation', 'dullness', 'anti-aging'],
    ingredients: ['vitamin-c', 'peptides'],
    keyIngredients: ['vitamin-c'],
    rating: {
      overall: 4.5,
      texture: 3.5,
      efficacy: 5,
      value: 3,
      pros: ['Visible brightening', 'Skin glows', 'Protected antioxidant formula'],
      cons: ['Extremely expensive', 'Sticky texture', 'Short PAO', 'Oxidizes to orange'],
      notes: 'Results are undeniable but the price is hard to justify. Used half the bottle and saw real brightening.',
      adverseReactions: [],
      wouldRepurchase: false,
      reviewDate: '2024-07-10',
    },
    inRoutine: true,
    routineStep: 'am',
    routineOrder: 2,
    tags: ['brightening', 'antioxidant', 'luxury', 'anti-aging'],
  },
  {
    id: 'la-roche-spf',
    name: 'Anthelios Melt-In Milk SPF 100',
    brand: 'La Roche-Posay',
    category: 'spf',
    imageUrl: 'https://images.unsplash.com/photo-1556228578-8c89e6adf883?w=300&h=300&fit=crop',
    imageColor: '#F0F8FF',
    price: 36,
    size: '90ml',
    purchaseDate: '2024-01-10',
    openedDate: '2024-01-15',
    paoMonths: 12,
    concerns: ['anti-aging', 'hyperpigmentation', 'sensitivity'],
    ingredients: ['spf'],
    keyIngredients: ['spf'],
    rating: {
      overall: 4,
      texture: 4,
      efficacy: 5,
      value: 4,
      pros: ['High protection', 'Melts in nicely', 'No white cast', 'Lightweight for SPF 100'],
      cons: ['Can pill under makeup', 'Slight chemical sunscreen smell'],
      notes: 'Best chemical sunscreen I\'ve tried. Goes on smoothly and doesn\'t break me out.',
      adverseReactions: [],
      wouldRepurchase: true,
      reviewDate: '2024-05-20',
    },
    inRoutine: true,
    routineStep: 'am',
    routineOrder: 6,
    tags: ['spf', 'chemical', 'daily-use', 'broad-spectrum'],
  },
  {
    id: 'drunk-elephant-moisturizer',
    name: 'Protini Polypeptide Cream',
    brand: 'Drunk Elephant',
    category: 'moisturizer',
    imageUrl: 'https://images.unsplash.com/photo-1556229010-6c3f2c9ca5f8?w=300&h=300&fit=crop',
    imageColor: '#FFF5F5',
    price: 68,
    size: '50ml',
    purchaseDate: '2024-05-01',
    openedDate: '2024-05-05',
    paoMonths: 12,
    concerns: ['anti-aging', 'firmness', 'fine-lines', 'dryness'],
    ingredients: ['peptides', 'hyaluronic-acid', 'ceramides'],
    keyIngredients: ['peptides'],
    rating: {
      overall: 3.5,
      texture: 5,
      efficacy: 3,
      value: 2.5,
      pros: ['Beautiful texture', 'Absorbs well', 'Fragrance-free'],
      cons: ['Very expensive', 'Not sure if peptides are making a difference', 'Jar packaging exposes to air'],
      notes: 'Luxurious feel but hard to tell if it\'s doing more than a basic moisturizer. Pricey for what it is.',
      adverseReactions: [],
      wouldRepurchase: false,
      reviewDate: '2024-08-01',
    },
    inRoutine: true,
    routineStep: 'both',
    routineOrder: 5,
    tags: ['anti-aging', 'luxury', 'peptide-rich'],
  },
  {
    id: 'aha-bha-peeling',
    name: 'AHA 30% + BHA 2% Peeling Solution',
    brand: 'The Ordinary',
    category: 'exfoliant',
    imageUrl: 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=300&h=300&fit=crop',
    imageColor: '#FF6B6B',
    price: 9,
    size: '30ml',
    purchaseDate: '2024-02-15',
    openedDate: '2024-02-20',
    paoMonths: 12,
    concerns: ['texture', 'hyperpigmentation', 'acne', 'dullness'],
    ingredients: ['glycolic-acid', 'salicylic-acid'],
    keyIngredients: ['glycolic-acid', 'salicylic-acid'],
    rating: {
      overall: 4,
      texture: 3,
      efficacy: 4.5,
      value: 5,
      pros: ['Highly effective', 'Dramatically improves texture', 'Affordable', 'Visible results'],
      cons: ['Very intense — must be careful', 'Stings', 'Red for hours after'],
      notes: 'Use 1x/week max. Results are incredible for texture and brightness but must follow instructions carefully.',
      adverseReactions: ['Burning sensation (expected)', 'Redness for 2-3 hours post-use'],
      wouldRepurchase: true,
      reviewDate: '2024-07-15',
    },
    inRoutine: false,
    tags: ['exfoliant', 'chemical-peel', 'weekly-treatment', 'budget-friendly'],
  },
  {
    id: 'bioderma-toner',
    name: 'Sensibio Toner',
    brand: 'Bioderma',
    category: 'toner',
    imageUrl: 'https://images.unsplash.com/photo-1611080541599-8c6dbde6ed28?w=300&h=300&fit=crop',
    imageColor: '#F8F8FF',
    price: 24,
    size: '250ml',
    purchaseDate: '2024-03-15',
    openedDate: '2024-03-15',
    paoMonths: 12,
    concerns: ['sensitivity', 'redness', 'dryness'],
    ingredients: ['centella', 'hyaluronic-acid'],
    keyIngredients: ['centella'],
    rating: {
      overall: 4,
      texture: 4.5,
      efficacy: 3.5,
      value: 4,
      pros: ['Ultra gentle', 'Calming', 'Great for sensitive days', 'Light and refreshing'],
      cons: ['Minimal active ingredients', 'Subtle results only'],
      notes: 'Great as a first step after cleansing, especially on reactive skin days.',
      adverseReactions: [],
      wouldRepurchase: true,
      reviewDate: '2024-06-20',
    },
    inRoutine: true,
    routineStep: 'both',
    routineOrder: 2,
    tags: ['sensitive', 'calming', 'gentle', 'hydrating'],
  },
];

export const PROCEDURES: Procedure[] = [
  {
    id: 'proc-1',
    name: 'Clear + Brilliant Laser',
    category: 'laser',
    date: '2024-03-15',
    provider: 'Dr. Sarah Chen',
    clinic: 'Glow Dermatology',
    cost: 350,
    notes: 'First session. Mild redness for 2 days. Skin felt smoother after 1 week.',
    rating: 4,
    results: 'Improved texture, slight brightening. Pores looked smaller for 3-4 weeks.',
    nextAppointment: '2024-09-15',
    recommendedIntervalMonths: 6,
    sideEffects: ['Redness (2 days)', 'Mild peeling (day 3-4)'],
    concerns: ['texture', 'pores', 'dullness'],
    downtime: '2-3 days',
  },
  {
    id: 'proc-2',
    name: 'Botox - Forehead & Glabella',
    category: 'injectables',
    date: '2024-01-20',
    provider: 'Dr. James Park',
    clinic: 'Refresh Aesthetics',
    cost: 650,
    notes: '20 units. Results kicked in at day 5. Looked natural at the dose used.',
    rating: 5,
    results: 'Significant reduction in forehead lines and 11s. Looked very natural.',
    nextAppointment: '2024-04-20',
    recommendedIntervalMonths: 3,
    sideEffects: ['Mild bruising at one injection site'],
    concerns: ['fine-lines', 'anti-aging'],
    downtime: 'None',
  },
  {
    id: 'proc-3',
    name: 'HydraFacial',
    category: 'facials',
    date: '2024-04-10',
    provider: 'Lisa Martinez',
    clinic: 'The Spa at Four Seasons',
    cost: 200,
    notes: 'Included extraction and LED light add-on. Skin looked incredible immediately after.',
    rating: 5,
    results: 'Instant glow, cleaner pores, hydrated and dewy skin.',
    nextAppointment: '2024-07-10',
    recommendedIntervalMonths: 3,
    sideEffects: [],
    concerns: ['pores', 'dullness', 'dryness'],
    downtime: 'None',
  },
  {
    id: 'proc-4',
    name: 'Microneedling (1mm)',
    category: 'microneedling',
    date: '2024-05-20',
    provider: 'Dr. Sarah Chen',
    clinic: 'Glow Dermatology',
    cost: 400,
    notes: 'Applied numbing cream for 30 min prior. PRP not included this time.',
    rating: 4,
    results: 'Improved skin texture after 4 weeks. Good for overall skin quality.',
    recommendedIntervalMonths: 2,
    sideEffects: ['Redness (3 days)', 'Skin felt tight and dry for 5 days'],
    concerns: ['texture', 'anti-aging', 'firmness', 'pores'],
    downtime: '3-5 days',
  },
];

export const JOURNAL_ENTRIES: JournalEntry[] = [
  {
    id: 'j1',
    date: '2024-08-01',
    mood: 'great',
    skinCondition: 8,
    notes: 'Skin looking really glowy today. The retinol is paying off!',
    products: ['cerave-cleanser', 'paula-niacinamide', 'drunk-elephant-moisturizer', 'la-roche-spf'],
    concerns: [],
    environment: { weather: 'sunny', humidity: 'moderate', stress: 'low', sleep: 8 },
  },
  {
    id: 'j2',
    date: '2024-07-25',
    mood: 'bad',
    skinCondition: 4,
    notes: 'Breakout on chin — could be hormonal or from the new peptide cream. Skin feels reactive.',
    products: ['cerave-cleanser', 'drunk-elephant-moisturizer', 'la-roche-spf'],
    concerns: ['acne', 'sensitivity'],
    environment: { weather: 'hot', humidity: 'high', stress: 'high', sleep: 6 },
  },
  {
    id: 'j3',
    date: '2024-07-15',
    mood: 'okay',
    skinCondition: 6,
    notes: 'Did the AHA/BHA peel last night. Skin a bit sensitive today but smoother.',
    products: ['cerave-cleanser', 'bioderma-toner', 'drunk-elephant-moisturizer'],
    concerns: ['texture'],
    environment: { weather: 'cloudy', humidity: 'low', stress: 'medium', sleep: 7 },
  },
  {
    id: 'j4',
    date: '2024-07-01',
    mood: 'good',
    skinCondition: 7,
    notes: 'Pores looking smaller recently. Niacinamide doing its job!',
    products: ['cerave-cleanser', 'paula-niacinamide', 'ordinary-retinol', 'drunk-elephant-moisturizer', 'la-roche-spf'],
    concerns: ['pores'],
    environment: { weather: 'sunny', humidity: 'moderate', stress: 'low', sleep: 7.5 },
  },
];

export const DEFAULT_USER_PROFILE: UserProfile = {
  name: '',
  skinType: 'combination',
  skinConcerns: ['hyperpigmentation', 'pores', 'anti-aging'],
  allergies: [],
  knownIrritants: [],
  budget: 'mixed',
  onboarded: false,
  goals: ['Even skin tone', 'Minimize pores', 'Prevent aging'],
  procedureInterests: ['laser', 'injectables'],
};
